export const urlRoutes = {
  landingPage: "/",
  loanRequestForm: "/loanrequestform",
  editProfilePage: "/editprofilepage",
  profilePage: "/profilepage",
  loanDetailPage: "/loandetailpage",
  loggedInLandingLoansList: "/loggedinlandingloanslist",
  signupPage: "/signuppage",
  loginPage: "/loginpage",
  portfolioPage: "/portfoliopage",
  existingLoanDetailPage: "/existingloandetailpage",
};

export const loanStatus = {
  REQUESTED: "REQUESTED",
  EXPIRED: "EXPIRED",
  FILLED: "FILLED",
  COMPLETED: "COMPLETED",
  DISABLED: "DISABLED",
};

export const mockLoans = [
  {
    id: 1,
    borrowerName: "Vikas Ahuja",
    loanStatus: "REQUESTED",
    amount: "34000",
    interestRate: "8.75",
    payoutFrequency: "MONTHLY",
    emiStartDate: "",
    tenureMonths: "20",
    maturityDate: "",
    purpose: "Education",
    description: "Sample desc",
    expiryDate: "",
    createdAt: "",
    totalAmount: "42353.85",
  },
  {
    id: 2,
    borrowerName: "Amit Singh",
    loanStatus: "REQUESTED",
    amount: "89000",
    interestRate: "5.95",
    payoutFrequency: "MONTHLY",
    emiStartDate: "",
    tenureMonths: "56",
    maturityDate: "",
    purpose: "Education",
    description: "Sample desc",
    expiryDate: "",
    createdAt: "",
    totalAmount: "123556.95",
  },
  {
    id: 3,
    borrowerName: "Vivek Mishra",
    loanStatus: "REQUESTED",
    amount: "35450",
    interestRate: "6.90",
    payoutFrequency: "MONTHLY",
    emiStartDate: "",
    tenureMonths: "15",
    maturityDate: "",
    purpose: "Education",
    description: "Sample desc",
    expiryDate: "",
    createdAt: "",
    totalAmount: "38853.40",
  },
  {
    id: 3,
    borrowerName: "Vivek Mishra",
    loanStatus: "REQUESTED",
    amount: "35450",
    interestRate: "6.90",
    payoutFrequency: "MONTHLY",
    emiStartDate: "",
    tenureMonths: "15",
    maturityDate: "",
    purpose: "Education",
    description: "Sample desc",
    expiryDate: "",
    createdAt: "",
    totalAmount: "38853.40",
  },
  {
    id: 3,
    borrowerName: "Vivek Mishra",
    loanStatus: "REQUESTED",
    amount: "35450",
    interestRate: "6.90",
    payoutFrequency: "MONTHLY",
    emiStartDate: "",
    tenureMonths: "15",
    maturityDate: "",
    purpose: "Education",
    description: "Sample desc",
    expiryDate: "",
    createdAt: "",
    totalAmount: "38853.40",
  },
  {
    id: 3,
    borrowerName: "Vivek Mishra",
    loanStatus: "REQUESTED",
    amount: "35450",
    interestRate: "6.90",
    payoutFrequency: "MONTHLY",
    emiStartDate: "",
    tenureMonths: "15",
    maturityDate: "",
    purpose: "Education",
    description: "Sample desc",
    expiryDate: "",
    createdAt: "",
    totalAmount: "38853.40",
  },
  {
    id: 3,
    borrowerName: "Vivek Mishra",
    loanStatus: "REQUESTED",
    amount: "35450",
    interestRate: "6.90",
    payoutFrequency: "MONTHLY",
    emiStartDate: "",
    tenureMonths: "15",
    maturityDate: "",
    purpose: "Education",
    description: "Sample desc",
    expiryDate: "",
    createdAt: "",
    totalAmount: "38853.40",
  },
  {
    id: 3,
    borrowerName: "Vivek Mishra",
    loanStatus: "REQUESTED",
    amount: "35450",
    interestRate: "6.90",
    payoutFrequency: "MONTHLY",
    emiStartDate: "",
    tenureMonths: "15",
    maturityDate: "",
    purpose: "Education",
    description: "Sample desc",
    expiryDate: "",
    createdAt: "",
    totalAmount: "38853.40",
  },
  {
    id: 3,
    borrowerName: "Vivek Mishra",
    loanStatus: "REQUESTED",
    amount: "35450",
    interestRate: "6.90",
    payoutFrequency: "MONTHLY",
    emiStartDate: "",
    tenureMonths: "15",
    maturityDate: "",
    purpose: "Education",
    description: "Sample desc",
    expiryDate: "",
    createdAt: "",
    totalAmount: "38853.40",
  },
];
